runner:
  golint:
    cmd: golint ./...
    errorformat:
      - "%f:%l:%c: %m"
  govet:
    cmd: go tool vet -all -shadowstrict .
  unused:
    cmd: unused $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  staticcheck:
    cmd: staticcheck $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
